export const userName = "User06";
export const userUniqueId = "User06";
export const chatroomId = "4296660";
export const announcementRoomId = "4296659";
export const gender: string = "female";
export const backIconPath = require("../../assets/images/backIcon.png");
export const profileImageUrl = "";
export const backgroundImage = "";
export const imageCropIcon = "";
